api_platform:
    title: WR506 - API
    version: 1.0.0
    show_webby: false
    graphql:
        enabled: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    formats:
        jsonld: ['application/ld+json']
        multipart: ['multipart/form-data']
        json: ['application/json']
