# Rate limiter configuration
framework:
    rate_limiter:
        # Rate limiter for anonymous API users
        anonymous_api:
            policy: 'sliding_window'
            limit: 30
            interval: '1 minute'

        # Rate limiter for authenticated API users (default limit)
        authenticated_api:
            policy: 'token_bucket'
            limit: 100
            rate: {interval: '2 minutes', amount: 100}

